AllCops:
  NewCops: disable
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  AutoCorrect: false

Layout/LineLength:
  Max: 90
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 125
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Naming/FileName:
  Exclude:
    - Gemfile

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RescueModifier:
  AutoCorrect: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
