version: '3'
services:
  console:
    image: ruby:2.5
    volumes:
      - .:/app:z
    hostname: varanus-dev
    working_dir: /app
    stdin_open: true
    tty: true
    command: bash -c './bin/setup && ./bin/console'
